language: go

go: 
 - 1.7
 - tip

sudo: false

before_script:
  - go vet ./...

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
- go get github.com/golang/lint/golint

script:
- $HOME/gopath/bin/golint
- go test -v -covermode=count -coverprofile=profile.cov
- $HOME/gopath/bin/goveralls -service=travis-ci
