language: go

go: 
  - "1.12.x"
  - tip

matrix:
  allow_failures:
    - go: tip
fast_finish: true

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - go vet ./...
  - go test -v -race ./...
  - go test -v -cover -covermode=count -coverprofile=coverage.txt ./... > /dev/null

after_success:
  - bash <(curl -s https://codecov.io/bash)
