on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Tests
        run: go test -race ./...
